# Generated by Django 2.0.5 on 2018-05-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='herd')),
            ],
            options={
                'verbose_name': 'Herd',
                'verbose_name_plural': 'Herds',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='herd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock.Herd'),
        ),
    ]
